title: Welcome to Xuhui HU's Space 
theme: jekyll-theme-cayman
description: I'm a Ph.D. candidate majoring in the research of Bionic Prostheses since 2016, focusing on sEMG based motion recognition.
show_downloads: true
google_analytics:
